In [1]:
import pandas as pd
import os

In [2]:
os.chdir('..')

In [3]:
base_folder = 'data'

In [4]:
# Get a list of all subfolders in the base folder
subfolders = [f.path for f in os.scandir(base_folder) if f.is_dir()]

In [9]:
all_merged_datas = []  # List to store merged dataframes

In [10]:
# Iterate through each subfolder
for subfolder in subfolders:
    try:
        # Construct the file paths for each CSV within the subfolder
        totals_path = os.path.join(subfolder, 'Totals.csv')
        chart_path = os.path.join(subfolder, 'Chart data.csv')
        table_path = os.path.join(subfolder, 'Table data.csv')

        # Read CSV files with error handling
        try:
            totals_data = pd.read_csv(totals_path)
        except FileNotFoundError:
            totals_data = pd.DataFrame({'Date': [], 'Views': []})

        try:
            chart_data = pd.read_csv(chart_path)
        except FileNotFoundError:
            chart_data = pd.DataFrame({'Date': [], 'Cities': [], 'City name': [], 'Views': []})

        try:
            table_data = pd.read_csv(table_path)
        except FileNotFoundError:
            table_data = pd.DataFrame({'Cities': [], 'City name': [], 'Geography': [], 'Views': [],
                                       'Watch time (hours)': [], 'Average view duration': []})

        # Find common columns dynamically
        common_columns = set(chart_data.columns) & set(table_data.columns)

        # Check if there are common columns
        if common_columns:
            # Merge based on the common columns
            merged_data = pd.merge(chart_data, table_data, on=list(common_columns), how='left')

            # Merge the result with the "Totals" data based on the "Date" column
            final_data = pd.merge(merged_data, totals_data, on='Date', how='left')

            # Append the merged dataframe to the list
            all_merged_datas.append(final_data)

            # Display the final merged data for the current subfolder
            print(f'\nMerged Data for {subfolder}:')
            print(final_data)

            # Save the merged data to a new CSV file within each subfolder
            output_path = os.path.join(subfolder, 'merged_data.csv')
            final_data.to_csv(output_path, index=False)
        else:
            print(f"Skipping {subfolder}: No common columns found between chart_data and table_data.")

    except Exception as e:
        print(f"Error processing {subfolder}: {str(e)}")

print("\nProcessing complete.")

Merged Data for data/Sharing service:
             Date             Sharing service  Shares_x  Shares_y
0      2020-06-28                    Facebook         0         0
1      2020-06-29                    Facebook         0         1
2      2020-06-30                    Facebook         0         0
3      2020-07-01                    Facebook         0         0
4      2020-07-02                    Facebook         0         0
...           ...                         ...       ...       ...
11506  2023-12-24  Share to WhatsApp Business         0         0
11507  2023-12-25  Share to WhatsApp Business         0         0
11508  2023-12-26  Share to WhatsApp Business         0         0
11509  2023-12-27  Share to WhatsApp Business         0         0
11510  2023-12-28  Share to WhatsApp Business         0         0

[11511 rows x 4 columns]
Skipping data/Viewer age: No common columns found between chart_data and table_data.

Merged Data for data/Cities:
            Date                                 Cities    City name  Views_x  \
0     2020-06-28  0x164b85cef5ab402d:0x8467b6b037a24d49  Addis Ababa        0
1     2020-06-29  0x164b85cef5ab402d:0x8467b6b037a24d49  Addis Ababa        0
2     2020-06-30  0x164b85cef5ab402d:0x8467b6b037a24d49  Addis Ababa        0
3     2020-07-01  0x164b85cef5ab402d:0x8467b6b037a24d49  Addis Ababa        0
4     2020-07-02  0x164b85cef5ab402d:0x8467b6b037a24d49  Addis Ababa        0
...          ...                                    ...          ...      ...
6390  2023-12-24  0x487a4d4c5226f5db:0xd9be143804fe6baa   Manchester        0
6391  2023-12-25  0x487a4d4c5226f5db:0xd9be143804fe6baa   Manchester        0
6392  2023-12-26  0x487a4d4c5226f5db:0xd9be143804fe6baa   Manchester        0
6393  2023-12-27  0x487a4d4c5226f5db:0xd9be143804fe6baa   Manchester        0
6394  2023-12-28  0x487a4d4c5226f5db:0xd9be143804fe6baa   Manchester        0

     Geography Geography.1  Watch time (hours) Average view duration  Views_y
0          NaN         NaN                 NaN                   NaN        1
1          NaN         NaN                 NaN                   NaN       72
2          NaN         NaN                 NaN                   NaN       76
3          NaN         NaN                 NaN                   NaN       70
4          NaN         NaN                 NaN                   NaN       57
...        ...         ...                 ...                   ...      ...
6390       NaN         NaN                 NaN                   NaN       36
6391       NaN         NaN                 NaN                   NaN       24
6392       NaN         NaN                 NaN                   NaN       57
6393       NaN         NaN                 NaN                   NaN        8
6394       NaN         NaN                 NaN                   NaN       25

[6395 rows x 9 columns]

Merged Data for data/Subscription status:
            Date Subscription status  Views_x  Watch time (hours)  \
0     2020-06-28          Subscribed        1                 NaN
1     2020-06-29          Subscribed       16                 NaN
2     2020-06-30          Subscribed       23                 NaN
3     2020-07-01          Subscribed       23                 NaN
4     2020-07-02          Subscribed       26                 NaN
...          ...                 ...      ...                 ...
2553  2023-12-24      Not subscribed        9                 NaN
2554  2023-12-25      Not subscribed       11                 NaN
2555  2023-12-26      Not subscribed       25                 NaN
2556  2023-12-27      Not subscribed        5                 NaN
2557  2023-12-28      Not subscribed        2                 NaN

     Average view duration  Views_y
0                      NaN        1
1                      NaN       72
2                      NaN       76
3                      NaN       70
4                      NaN       57
...                    ...      ...
2553                   NaN       36
2554                   NaN       24
2555                   NaN       57
2556                   NaN        8
2557                   NaN       25

[2558 rows x 6 columns]

Merged Data for data/Geography:
             Date Geography  Views_x  Watch time (hours)  \
0      2020-06-28        BJ        0                 NaN
1      2020-06-29        BJ        0                 NaN
2      2020-06-30        BJ        0                 NaN
3      2020-07-01        BJ        0                 NaN
4      2020-07-02        BJ        0                 NaN
...           ...       ...      ...                 ...
37086  2023-12-24        ZA        0                 NaN
37087  2023-12-25        ZA        0                 NaN
37088  2023-12-26        ZA        0                 NaN
37089  2023-12-27        ZA        0                 NaN
37090  2023-12-28        ZA        0                 NaN

      Average view duration  Views_y
0                       NaN        1
1                       NaN       72
2                       NaN       76
3                       NaN       70
4                       NaN       57
...                     ...      ...
37086                   NaN       36
37087                   NaN       24
37088                   NaN       57
37089                   NaN        8
37090                   NaN       25

[37091 rows x 6 columns]

Merged Data for data/Device type:
            Date Device type  Views_x  Watch time (hours)  \
0     2020-06-28    Computer        1                 NaN
1     2020-06-29    Computer       49                 NaN
2     2020-06-30    Computer       62                 NaN
3     2020-07-01    Computer       46                 NaN
4     2020-07-02    Computer       29                 NaN
...          ...         ...      ...                 ...
5111  2023-12-24      Tablet        0                 NaN
5112  2023-12-25      Tablet        0                 NaN
5113  2023-12-26      Tablet        0                 NaN
5114  2023-12-27      Tablet        0                 NaN
5115  2023-12-28      Tablet        0                 NaN

     Average view duration  Views_y
0                      NaN        1
1                      NaN       72
2                      NaN       76
3                      NaN       70
4                      NaN       57
...                    ...      ...
5111                   NaN       36
5112                   NaN       24
5113                   NaN       57
5114                   NaN        8
5115                   NaN       25

[5116 rows x 6 columns]
Skipping data/Viewer gender: No common columns found between chart_data and table_data.

Merged Data for data/Subtitles and CC:
             Date Subtitles and CC  Views_x  Watch time (hours)  \
0      2020-06-28              NaN        1                 NaN
1      2020-06-29              NaN       70                 NaN
2      2020-06-30              NaN       76                 NaN
3      2020-07-01              NaN       70                 NaN
4      2020-07-02              NaN       57                 NaN
...           ...              ...      ...                 ...
10227  2023-12-24              pt#        0                 NaN
10228  2023-12-25              pt#        0                 NaN
10229  2023-12-26              pt#        0                 NaN
10230  2023-12-27              pt#        0                 NaN
10231  2023-12-28              pt#        0                 NaN

      Average view duration  Views_y
0                       NaN        1
1                       NaN       72
2                       NaN       76
3                       NaN       70
4                       NaN       57
...                     ...      ...
10227                   NaN       36
10228                   NaN       24
10229                   NaN       57
10230                   NaN        8
10231                   NaN       25

[10232 rows x 6 columns]

Merged Data for data/Content type:
            Date Content type  Views_x  Watch time (hours)  \
0     2020-06-28        Other        0                 NaN
1     2020-06-29        Other        0                 NaN
2     2020-06-30        Other        0                 NaN
3     2020-07-01        Other        0                 NaN
4     2020-07-02        Other        0                 NaN
...          ...          ...      ...                 ...
2553  2023-12-24       Videos       36                 NaN
2554  2023-12-25       Videos       33                 NaN
2555  2023-12-26       Videos       57                 NaN
2556  2023-12-27       Videos        8                 NaN
2557  2023-12-28       Videos       25                 NaN

     Average view duration  Views_y
0                      NaN        1
1                      NaN       72
2                      NaN       76
3                      NaN       70
4                      NaN       57
...                    ...      ...
2553                   NaN       36
2554                   NaN       24
2555                   NaN       57
2556                   NaN        8
2557                   NaN       25

[2558 rows x 6 columns]

Merged Data for data/New and returning viewers:
            Date New and returning viewers  Views_x  Watch time (hours)  \
0     2020-06-28                   Unknown        1                 NaN
1     2020-06-29                   Unknown       72                 NaN
2     2020-06-30                   Unknown       76                 NaN
3     2020-07-01                   Unknown       70                 NaN
4     2020-07-02                   Unknown       57                 NaN
...          ...                       ...      ...                 ...
3832  2023-12-24         Returning viewers       33                 NaN
3833  2023-12-25         Returning viewers       24                 NaN
3834  2023-12-26         Returning viewers       41                 NaN
3835  2023-12-27         Returning viewers        3                 NaN
3836  2023-12-28         Returning viewers        0                 NaN

     Average view duration  Views_y
0                      NaN        1
1                      NaN       72
2                      NaN       76
3                      NaN       70
4                      NaN       57
...                    ...      ...
3832                   NaN       36
3833                   NaN       24
3834                   NaN       57
3835                   NaN        8
3836                   NaN       25

[3837 rows x 6 columns]

Merged Data for data/Subscription source:
             Date Subscription source  Subscribers_x  Subscribers gained  \
0      2020-06-28               Other              0                 NaN
1      2020-06-29               Other              0                 NaN
2      2020-06-30               Other              0                 NaN
3      2020-07-01               Other              0                 NaN
4      2020-07-02               Other              1                 NaN
...           ...                 ...            ...                 ...
10227  2023-12-24      YouTube search              0                 NaN
10228  2023-12-25      YouTube search              0                 NaN
10229  2023-12-26      YouTube search              0                 NaN
10230  2023-12-27      YouTube search              0                 NaN
10231  2023-12-28      YouTube search              0                 NaN

       Subscribers lost  Subscribers_y
0                   NaN              1
1                   NaN             13
2                   NaN              4
3                   NaN              2
4                   NaN              2
...                 ...            ...
10227               NaN              0
10228               NaN              1
10229               NaN              0
10230               NaN              0
10231               NaN              0

[10232 rows x 6 columns]

Merged Data for data/Operating system:
             Date Operating system  Views_x  Watch time (hours)  \
0      2020-06-28          Unknown        0                 0.0
1      2020-06-29          Unknown        0                 0.0
2      2020-06-30          Unknown        0                 0.0
3      2020-07-01          Unknown        0                 0.0
4      2020-07-02          Unknown        0                 0.0
...           ...              ...      ...                 ...
20459  2023-12-24        Chrome OS        0                 NaN
20460  2023-12-25        Chrome OS        0                 NaN
20461  2023-12-26        Chrome OS        0                 NaN
20462  2023-12-27        Chrome OS        0                 NaN
20463  2023-12-28        Chrome OS        0                 NaN

      Average view duration  Views_y
0                       NaN        1
1                       NaN       72
2                       NaN       76
3                       NaN       70
4                       NaN       57
...                     ...      ...
20459                   NaN       36
20460                   NaN       24
20461                   NaN       57
20462                   NaN        8
20463                   NaN       25

[20464 rows x 6 columns]

Merged Data for data/Viewership by Date:
Empty DataFrame
Columns: [Cities, City name, Views_x, Watch time (hours), Average view duration, Date, Views_y]
Index: []

Merged Data for data/Traffic source:
             Date     Traffic source  Views_x  Watch time (hours)  \
0      2020-06-28  Direct or unknown        0                 NaN
1      2020-06-29  Direct or unknown        6                 NaN
2      2020-06-30  Direct or unknown        2                 NaN
3      2020-07-01  Direct or unknown        3                 NaN
4      2020-07-02  Direct or unknown        0                 NaN
...           ...                ...      ...                 ...
11506  2023-12-24      Notifications        1                 NaN
11507  2023-12-25      Notifications        2                 NaN
11508  2023-12-26      Notifications        4                 NaN
11509  2023-12-27      Notifications        0                 NaN
11510  2023-12-28      Notifications        2                 NaN

      Average view duration  Impressions  Impressions click-through rate (%)  \
0                       NaN          NaN                                 NaN
1                       NaN          NaN                                 NaN
2                       NaN          NaN                                 NaN
3                       NaN          NaN                                 NaN
4                       NaN          NaN                                 NaN
...                     ...          ...                                 ...
11506                   NaN          NaN                                 NaN
11507                   NaN          NaN                                 NaN
11508                   NaN          NaN                                 NaN
11509                   NaN          NaN                                 NaN
11510                   NaN          NaN                                 NaN

       Views_y
0            1
1           72
2           76
3           70
4           57
...        ...
11506       36
11507       24
11508       57
11509        8
11510       25

[11511 rows x 8 columns]

Processing complete.

In [11]:
# Concatenate all merged datas into a single dataframe
if all_merged_datas:
    all_merged_data = pd.concat(all_merged_datas, ignore_index=True)

    # Display the final concatenated dataframe
    print("\nConcatenated Data:")
    print(all_merged_data)

    # Save the concatenated dataframe to a new CSV file
    all_output_path = os.path.join("data", 'all_merged_data.csv')
    all_merged_data.to_csv(all_output_path, index=False)
else:
    print("No common columns found in any subfolder.")

Concatenated Data:
              Date Sharing service  Shares_x  Shares_y Cities City name  \
0       2020-06-28        Facebook       0.0       0.0    NaN       NaN
1       2020-06-29        Facebook       0.0       1.0    NaN       NaN
2       2020-06-30        Facebook       0.0       0.0    NaN       NaN
3       2020-07-01        Facebook       0.0       0.0    NaN       NaN
4       2020-07-02        Facebook       0.0       0.0    NaN       NaN
...            ...             ...       ...       ...    ...       ...
121500  2023-12-24             NaN       NaN       NaN    NaN       NaN
121501  2023-12-25             NaN       NaN       NaN    NaN       NaN
121502  2023-12-26             NaN       NaN       NaN    NaN       NaN
121503  2023-12-27             NaN       NaN       NaN    NaN       NaN
121504  2023-12-28             NaN       NaN       NaN    NaN       NaN

        Views_x Geography Geography.1  Watch time (hours)  ...  \
0           NaN       NaN         NaN                 NaN  ...
1           NaN       NaN         NaN                 NaN  ...
2           NaN       NaN         NaN                 NaN  ...
3           NaN       NaN         NaN                 NaN  ...
4           NaN       NaN         NaN                 NaN  ...
...         ...       ...         ...                 ...  ...
121500      1.0       NaN         NaN                 NaN  ...
121501      2.0       NaN         NaN                 NaN  ...
121502      4.0       NaN         NaN                 NaN  ...
121503      0.0       NaN         NaN                 NaN  ...
121504      2.0       NaN         NaN                 NaN  ...

       New and returning viewers  Subscription source Subscribers_x  \
0                            NaN                  NaN           NaN
1                            NaN                  NaN           NaN
2                            NaN                  NaN           NaN
3                            NaN                  NaN           NaN
4                            NaN                  NaN           NaN
...                          ...                  ...           ...
121500                       NaN                  NaN           NaN
121501                       NaN                  NaN           NaN
121502                       NaN                  NaN           NaN
121503                       NaN                  NaN           NaN
121504                       NaN                  NaN           NaN

       Subscribers gained Subscribers lost Subscribers_y Operating system  \
0                     NaN              NaN           NaN              NaN
1                     NaN              NaN           NaN              NaN
2                     NaN              NaN           NaN              NaN
3                     NaN              NaN           NaN              NaN
4                     NaN              NaN           NaN              NaN
...                   ...              ...           ...              ...
121500                NaN              NaN           NaN              NaN
121501                NaN              NaN           NaN              NaN
121502                NaN              NaN           NaN              NaN
121503                NaN              NaN           NaN              NaN
121504                NaN              NaN           NaN              NaN

       Traffic source  Impressions  Impressions click-through rate (%)
0                 NaN          NaN                                 NaN
1                 NaN          NaN                                 NaN
2                 NaN          NaN                                 NaN
3                 NaN          NaN                                 NaN
4                 NaN          NaN                                 NaN
...               ...          ...                                 ...
121500  Notifications          NaN                                 NaN
121501  Notifications          NaN                                 NaN
121502  Notifications          NaN                                 NaN
121503  Notifications          NaN                                 NaN
121504  Notifications          NaN                                 NaN

[121505 rows x 26 columns]

In [13]:
all_merged_data

,Date,Sharing service,Shares_x,Shares_y,Cities,City name,Views_x,Geography,Geography.1,Watch time (hours),...,New and returning viewers,Subscription source,Subscribers_x,Subscribers gained,Subscribers lost,Subscribers_y,Operating system,Traffic source,Impressions,Impressions click-through rate (%)
0,2020-06-28,Facebook,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-06-29,Facebook,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-06-30,Facebook,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-07-01,Facebook,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-07-02,Facebook,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121500,2023-12-24,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Notifications,NaN,NaN
121501,2023-12-25,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Notifications,NaN,NaN
121502,2023-12-26,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Notifications,NaN,NaN
121503,2023-12-27,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Notifications,NaN,NaN
121504,2023-12-28,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Notifications,NaN,NaN